# Generated by Django 3.1.1 on 2020-11-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0039_auto_20200429_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
