# Generated by Django 3.1.1 on 2020-11-16 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xamine', '0040_order_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_addr',
            field=models.EmailField(default=False, max_length=254),
            preserve_default=False,
        ),
    ]
